### ISSUE TITLE
Nulls Last

### ISSUE THREAD

**Issue by krazyjakee** [laserlemon/periscope#11]
Hi there!

I'm wondering how when sorting on a specific column, how I can push all null values to the end, independent of sort direction.

**Comment by laserlemon** [comment]
Hi @krazyjakee! That's a question for your specific database rather than for Periscope. For instance, here's the documentation for PostgreSQL: https://www.postgresql.org/docs/9.5/static/queries-order.html

``` sql
SELECT select_list FROM table_expression ORDER BY sort_expression1 ASC NULLS LAST
```

Googling around should give you what you want! In a Rails context, you may want to use Arel to build and add the `NULLS FIRST/LAST` clause to your query ordering. Good luck!

**Comment by krazyjakee** [comment]
I am throwing the query parameters into periscopes black box which also handles sorting.

`.periscope(request.query_parameters)`

Are there no extra options I can pass to ask periscope to tweak the ordering?

EDIT: Update the model. Of course, got it. Thank you for taking the time.

**Comment by laserlemon** [comment]
Periscope is only an interface to whatever scopes your model already defines. How your models'  scopes handle ordering is a question I can't answer. Periscope will happily use whatever scope you define. If you want to give an example of parameters you're passing in, maybe I can help point you in the right direction.

**Comment by krazyjakee** [comment]
You're super kind, thank you. It suddenly hit me as it should have hours ago 👯 

Still getting used to rails, thank you again.
